### ISSUE TITLE
LU 06: Karten produzieren

### ISSUE THREAD

**Issue by NiklasSchg** [Peace-Research-Institute-Frankfurt/websites#520]
- [x] Für Podcast 06.01 und LU: Karte des Tlatelolco Treaty. Quelle: https://www.un.org/nwfz/content/treaty-tlatelolco
- [x] Für Podcast 06.02 und LU: Treaty of Pelindaba. Quelle: https://www.un.org/nwfz/content/treaty-pelindaba
- [x] Für Podcast 06.02 und LU: Treaty of Bangkok. Quelle: https://www.un.org/nwfz/fr/content/treaty-bangkok
- [x] Für Podcast 06.02 und LU: Treaty of Ratotonga. Quelle: https://www.un.org/nwfz/fr/content/treaty-rarotonga
- [x] Für Podcast 06.02 und LU: Central Asian Nuclear-Weapon-Free Zone Treaty. Quelle: https://www.un.org/nwfz/content/treaty-nuclear-weapon-free-zone-central-asia 
- [x] Für Podcast 06.02 und LU: Übersichtskarte, in der ALLE NWFZs farblich unterschiedlich markiert sind 
- [x] Für Podcast 06.03 und LU: Übersichtskarte, in der ALLE NWFZs farblich unterschiedlich markiert sind und die jeweiligen Zonen mit Namen benannt sind 

Alle Karten in den Ordner "Assets für PC" legen.

**Comment by awesomephant** [comment]
All done, closing.

- Quelldatei: https://www.figma.com/file/aHrqKw47bSatLAhN8WMOL3/EUNPDC-eLearning?type=design&node-id=0%3A1&mode=design&t=pOFdlyfcWhLrcIlp-1
- Exporte liegen in: https://www.dropbox.com/scl/fo/7ubed7he67svuno3p691j/h?rlkey=fznz5skeklqo8u0gad6nky474&dl=0
