### ISSUE TITLE
LU 15: Karte für Podcast 5

### ISSUE THREAD

**Issue by NiklasSchg** [Peace-Research-Institute-Frankfurt/websites#532]
![grafik](https://github.com/Peace-Research-Institute-Frankfurt/websites/assets/114146441/e554cf03-e132-4122-ab10-1e7872d6b145)

[  ] Karte von Ländern mit AI Strategy in unserem Design - leider per Hand --> Name: "Map-AI Strategies"
Vielleicht auch nach Jahr? 
Source: https://drive.google.com/drive/folders/1aw4YQlV-zbqsurzqOC6e-Fu_RgkU9Q8z

**Comment by awesomephant** [comment]
All in `/EUNPDC/Redesign/LU15/Podcasts/Assets für PC`
