### ISSUE TITLE
LU 05: Podcast 5 - Karte US Nuklearwaffen

### ISSUE THREAD

**Issue by NiklasSchg** [Peace-Research-Institute-Frankfurt/websites#607]
Karte basierend auf dieser Info für Podcast 5 erstellen und in den Asset-Ordner legen

"five US allies (Belgium, Germany, Italy, Turkey and the Netherlands) continue to host US tactical nuclear weapons"

Thx!

**Comment by awesomephant** [comment]
Datei: https://www.dropbox.com/scl/fi/lsfhabm7vmtcoffgy7v4y/eu-nukes-edit.png?rlkey=83a5n7gh70hsmobchbqnd7ghx&dl=0
