### ISSUE TITLE
Create list of possible Moodle question types

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/websites#760]

**Comment by eayan** [comment]
Moodle question types recommended.

These types of questions do not require further processing for grading:
Multiple choice
True/False
Cloze
Numerical
Match
Order

These types of questions may need further processing by the auhtor in terms of grading. Perhaps we may avoid doing this in our current context:
Essay
Short answer
Description

All sample questions are here: [https://moodlexml.fly.dev/info/help#samples](https://moodlexml.fly.dev/info/help#samples)
